app_paths:
    processed_log_files: "PROCESSED_FILES"  
    customers_source_base: "D:/LefebvreFileSync_ServerParser/test"
    archive_folder : "files"
watcher:
    directory: "LogRsync"
scheduler:
    time_interval: 30
logging:
    filename: "monitor.log"
    level: DEBUG
    archive: "archive_logging"
error:
    filename: "error.log"
    archive: "archive_error"
queue:
    processing_queue: yes
    time: 0.1 
    maxsize: 3     
other:
    max_retries: 10
    timeout: 60
    endpoint_to_check : "https://led-qa-api-lexon.lefebvre.es"  
    # https://herculesppd.lefebvre.es     
    # https://online.elderecho.com for production
    # QA -> https://led-qa-api-lexon.lefebvre.es
    # PRO -> https://api.lex-on.es